name: CI

on:
  push:
    branches: [ master ]
#    tags:
#      - '!*'
#    paths:
#      - gelfjs/*
#      - tests/*
#  pull_request:
#    branches: [ master ]
#    paths:
#      - '!*.MD'

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macOS-latest ]
        node: [ '12' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: |
        npm install
        npm test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: |
        npm install
    - uses: paambaati/codeclimate-action@v2.5.5
      env:
        CC_TEST_REPORTER_ID: a262dc82b33d987337a92bbd7089fdcac0cf5ab63097e247c32ccc27e661391f
      with:
        coverageCommand: npm run coverage
